### ISSUE TITLE
Integrate to upstream bash completion project

### ISSUE THREAD

**Issue by alive4ever** [2ion/mpv-bash-completion#10]
It would be better to submit mpv completion to [upstream bash-completion project](https://github.com/scop/bash-completion) periodically so that more users will enjoy having bash completion for mpv command.

**Comment by 2ion** [comment]
IMHO this is not a very good idea as a completion definition built against version B of mpv can (almost certainly will) be broken when used with mpv version A or version C since upstream is frequently changing around, redefining and removing options. Because mpv is a moving target, shipping a universal static completion file the functionality of which goes beyond basic file name completion is bound to be completely broken all the time.

Since my completion e.g. also completes arguments to AV filters which also frequently change, or are added or removed, this concern also applies here. Not even to speak of different distributions packaging wildly different versions of mpv (like 0.6.2 in Debian Jessie or 0.14 in Ubuntu Xenial or 0.18 in Debian unstable) which have lots of incompatible options and the impact of feature differences due different dependencies detected at compile time.

This project is just a duct tape-like hack which I wouldn't even consider for inclusion into the upstream project; there are lots of bugs in the current version, mostly because mpv itself doesn't manage to type their options in a consistent fashion (as in #8 ). No idea if the zsh completion that is included in the project is better or worse because I'm not using it.

As soon as mpv exposes the full option table including all types and choices via its Lua API, I shall be writing a dynamic completion query tool which gets all available options from the installed mpv version and thus can offer a working solution across different versions of mpv with a code base that works against each of them.
